// ui/components/index.js
export App from './App/App'
export Home from './Home'
export Pages from './Pages/Index'
export ShowPage from './Pages/Show'
export MySidebar from './App/MySidebar'
export Login from './Pages/Login'
export Register from './Pages/Register'
export History from './Pages/History'
export Payment from './Pages/Payment'
export Notification from './Pages/Notification'
export Settings from './Pages/Settings'
export About from './Pages/About'
